######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 2 12:08:15 2008
######################################################################

CONFIG += qtestlib
CONFIG += debug

# Input
TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += /usr/include/qt4/
INCLUDEPATH += ..

# Input
HEADERS += ../../libtcpclient++/test/TcpSendFile.h
SOURCES += FritzTest.cpp FBServer.cpp ../../libtcpclient++/test/TcpSendFile.cpp
LIBS    += ../libfritz++.a
LIBS    += -lccgnu2 -lccext2 -lgcrypt

libfritz.target   = fritz
libfritz.commands = make -C ..
QMAKE_EXTRA_TARGETS += libfritz
TARGETDEPS += fritz
